GET http://localhost:8000/api/recipes/ HTTP/1.1
content-type: application/json

{
}
###
POST http://127.0.0.1:8000/api/auth/token/login/ HTTP/1.1
content-type: application/json

{
    "password": "alpine12",
    "email": "aaa@3aa.aa"
}
###
POST http://localhost:8000/api/recipes/ HTTP/1.1
content-type: application/json
Authorization: Token 5d421368a0c3210c864329e6d8e7ec8044983edd

{
    "ingredients": [
        {
            "id": 1,
            "amount": 10
        }
    ],
    "tags": [
        1,
        2
    ],
    "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
    "name": "string",
    "text": "string",
    "cooking_time": 1
}
###
GET http://localhost:8000/api/tags/1/ HTTP/1.1
content-type: application/json
###
GET http://localhost:8000/api/ingredients/15/ HTTP/1.1
content-type: application/json
