POST http://localhost:8000/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "buttface",
    "first_name": "butt",
    "last_name": "face",
    "email": "butt@face.me",
    "password": "asstits01"
}
###
POST http://127.0.0.1:8000/api/auth/token/login/ HTTP/1.1
content-type: application/json

{
    "password": "asstits01",
    "email": "butt@face.me"
}
###
POST http://localhost:8000/api/recipes/ HTTP/1.1
content-type: application/json
Authorization: Token 903a40028fe64b4568403b2e425d569d3a2e4b6a

{
    "ingredients": [
        {
            "id": 1,
            "amount": 10
        },
        {
            "id": 2,
            "amount": 100
        }
    ],
    "tags": [
        1,
        2
    ],
    "image": "image_placeholder",
    "name": "test_recipe_name",
    "text": "test_recipe_text",
    "cooking_time": 99
}
###
GET http://localhost:8000/api/recipes/3/ HTTP/1.1
content-type: application/json
###
GET http://localhost:8000/api/ingredients/ HTTP/1.1
content-type: application/json
